<?php

namespace My\RssBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends EntityRepository
{
}
