<?php

namespace My\RssBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RssController__JMSInjector
{
    public static function inject($container) {
        $instance = new \My\RssBundle\Controller\RssController();
        return $instance;
    }
}
